### ISSUE TITLE
I can't login

### ISSUE THREAD

**Issue by hooddy** [basharast/Kodi-UWP-ARM#1]
It show me Client ID is incorrect error every time
![Untitled](https://user-images.githubusercontent.com/6899176/226160745-0f67d814-804f-4af2-9064-80d5a74946cb.png)

**Comment by basharast** [comment]
I guess you didn't setup your own API key:
[Check this link for guide](https://github.com/anxdpanic/plugin.video.youtube/wiki/Personal-API-Keys)

**Comment by hooddy** [comment]
yes i didn't

**Comment by hooddy** [comment]
I don't get how to set it up. I login into console. And next Im stuck. At step 2 video is removed for violation of some youtube rules. And next I can't find in any step Settings -> API etc menus in Kodi.

**Comment by basharast** [comment]
[Here video](https://www.youtube.com/watch?v=N18czV5tj5o) for creating YouTube API key 
You may get new options as the video is a bit old, just skip or continue without values.

When you get question about app type choose `TVs and Limited Input devices`

![TV1](https://user-images.githubusercontent.com/3244951/226498981-1b2b7f87-8231-45f3-8342-f420b1bd8883.PNG)

_______

After creating project and enabling `YouTube Data API` do the following..

## Keys (Google)
At the left there is `Credentials` (Click on it)
The video above is for `API Key` but you need also to create `OAuth 2.0 Client ID`
both can be created from `Create Credentials`
Check the picture below

![A1](https://user-images.githubusercontent.com/3244951/226496034-d43b4c59-e292-48c8-ab23-c5f7f05fe86f.PNG)

## API Page (Kodi)
For easy submitting these values, first from `YouTube` addon `Settings`
- Go to ` HTTP Server`
- At `Listen on IP` enter your device `IP` 
- or click on `Select listen IP` then select your device `Local IP`
- As for `Port` keep it or change it, no specific value

![B1](https://user-images.githubusercontent.com/3244951/226496484-f9b14947-a201-410e-abde-f64f8a2c505d.png)

Stay in `Settings` and go to `API` below
- Check `Enable API configuration page`

![B2](https://user-images.githubusercontent.com/3244951/226496617-37ebc798-6bb0-4ab0-830e-e5ba9300a9aa.png)

## Submit Keys (PC or any browser)
- Open any browser
- Go to configuration page `http://YOUR_DEVICE_IP:PORT/api`
- Fill the values as the picture below

![F1](https://user-images.githubusercontent.com/3244951/226496907-cdc1bd1e-4281-4141-b4b9-cdfaf6fc7101.PNG)

## Enable login (Google)
You may need to add your email to the `Test users`
- From ` OAuth consent screen`
- At `Test users` click `Add Users`
- Add your email then click `Save`

![L1](https://user-images.githubusercontent.com/3244951/226499533-acbdcd5d-f4cd-4944-bad4-09bce3409364.PNG)


**Note:** login is not required to watch videos you can use the addon without it once you setup the keys

Hope this will help.
